name: Validate Commit Messages

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed to fetch all commits in the PR

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Validate commit messages
        run: npx commitlint --from=origin/main --to=HEAD --verbose
