name: Validate Commit Messages

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed to fetch full commit history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Show commitlint config
        run: |
          ls -al
          cat commitlint.config.js

      - name: Validate commit messages
        run: |
          BASE=$(git merge-base origin/main HEAD)
          echo "Linting commits from $BASE to HEAD (excluding merge commits)"
          # get all commits excluding merge commits
          COMMITS=$(git log $BASE..HEAD --no-merges --pretty=format:%H)
          if [ -z "$COMMITS" ]; then
            echo "No non-merge commits to lint."
          else
            for commit in $COMMITS; do
              npx commitlint --from=$commit~1 --to=$commit --verbose
            done
          fi

