name: Validate Commit Messages

on:
  pull_request: {}

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed to fetch full commit history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Show commitlint config
        run: |
          ls -al
          cat commitlint.config.js

      - name: Validate latest commit only
        run: |
          LAST_COMMIT=$(git rev-parse HEAD)
          echo "Linting only the latest commit: $LAST_COMMIT"
          git show -s --format=%B $LAST_COMMIT | npx commitlint --verbose --from=$LAST_COMMIT --to=$LAST_COMMIT
    
