name: Changelog & Version Bump

on:
  push:
    branches: [main]

jobs:
  release:
    name: Semantic Version & Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Semantic Release & Plugins
        run: |
          npm install -g \
            semantic-release \
            conventional-changelog-conventionalcommits \
            @semantic-release/changelog \
            @semantic-release/git

      - name: Generate Changelog & Bump Version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Run semantic-release (automatic version bump + changelog)
          npx semantic-release

      - name: Commit changes if any
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json CHANGELOG.md
          git commit -m "chore(release): bump version & update changelog [skip ci]" || echo "No changes to commit"
          git push origin main
